name: Unit 2
on: [push]

# Default env values for Blue deployments
env:
  PORT: 8080
  APP_VERSION: 1.0.0
  BLUE_GREEN: blue

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Package Application (Build Image)
        run: |
          echo "Executing application compilation and container packaging..."
          docker build --tag retailstream:${{ env.APP_VERSION }} .
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      # Step 2: Complete this job by implementing the below steps

      - name: Execute Blue/Green Deployment

      - name: Healthcheck